/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Psychloor (https://sketchfab.com/blomqvistkevin)
license: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
source: https://sketchfab.com/models/01d397417f614dd2aa5b5d30160f13fb
title: Wooden Medieval Mace
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { Canvas, useFrame } from '@react-three/fiber'

export default function Model({ ...props }) {
  const groupRot = useRef()
  const groupPos = useRef()
  const { nodes, materials } = useGLTF('/weapows/mace/scene.gltf')

  useFrame((state, delta) => (groupPos.current.position.z = zoomLevel))
  useFrame((state, delta) => (groupRot.current.rotation.y -= 0.01))



  const [zoomLevel, setZoomLevel] = useState(-6);

  return (
    <group
      onPointerOver={() => setZoomLevel(.7)}
      onPointerOut={() => setZoomLevel(-6)}
      ref={groupPos} {...props} dispose={null}
    >

      <group scale={[4, 4, 4]} rotation={[0, 1, 0.6]} position={[1, -1, 0]} >
        <group ref={groupRot} {...props} dispose={null}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={nodes.defaultMaterial.material} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={nodes.defaultMaterial_1.material} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={nodes.defaultMaterial_2.material} />
          <mesh geometry={nodes.defaultMaterial_3.geometry} material={nodes.defaultMaterial_3.material} />
          <mesh geometry={nodes.defaultMaterial_4.geometry} material={nodes.defaultMaterial_4.material} />
        </group>
      </group >
    </group >

  )
}

useGLTF.preload('/scene.gltf')
