/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Artem Mykhailov (https://sketchfab.com/CGArtem)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/medieval-shield-b98b8f64d935415aab0fe9b70074511f
title: Medieval Shield
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { Canvas, useFrame } from '@react-three/fiber'

export default function Model({ ...props }) {
  const groupRot = useRef()
  const groupPos = useRef()
  const { nodes, materials } = useGLTF('/weapows/shield/scene.gltf')
  useFrame((state, delta) => (groupPos.current.position.z = zoomLevel))

  useFrame((state, delta) => (groupRot.current.rotation.z -= 0.01))
  const [zoomLevel, setZoomLevel] = useState(-6);


  return (
    <group
      onPointerOver={() => setZoomLevel(.7)}
      onPointerOut={() => setZoomLevel(-6)}
      ref={groupPos} {...props} dispose={null}
    >
      <group scale={[5, 5, 5]} rotation={[1.9, 0, 0]} position={[0, 0, 0]}>
        <group ref={groupRot} {...props} dispose={null}>
          <mesh
            geometry={nodes.SM_Medieval_Shield_M_Medieval_Shield_0.geometry}
            material={materials.M_Medieval_Shield}

          />
        </group>
      </group>

    </group>

  )
}

useGLTF.preload('/shield.gltf')
