/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Júlio Néctar (https://sketchfab.com/julioooc)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/spacecraft-no02sc-20790fc0b72146139cbefb553d9461d3
title: SpaceCraft Nº02SC
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { Canvas, useFrame } from '@react-three/fiber'


export default function Model({ ...props }) {
  const { nodes, materials } = useGLTF('/ships/ship1/scene.gltf')
  const groupRot = useRef()
  const groupPos = useRef()
  useFrame((state, delta) => (groupPos.current.position.z = 0))
  useFrame((state, delta) => (groupRot.current.rotation.y -= 0.01))
  const [zoomLevel, setZoomLevel] = useState(-6);


  return (
    <group
      onPointerOver={() => setZoomLevel(-1)}
      onPointerOut={() => setZoomLevel(-6)}
      ref={groupPos} {...props} dispose={null}
    >
      <group scale={[3, 3, 3]} rotation={[0, 0, 0]} position={[0, 0, 0]}>
        <group ref={groupRot} {...props} dispose={null}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.DefaultMaterial} material-opacity={0.5} />
        </group>
      </group>
    </group>

  )
}

useGLTF.preload('/scene.gltf')
